// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Bridge__ElementController from "./bridge/element_controller"
application.register("bridge--element", Bridge__ElementController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)
